version: '2'

services:

    # Container that emits nginx access logs randomly
    #
    # The variable LOG_LINES_PER_MINUTE defines the (approx.) frequency
    # of log line emission. (2/sec in this case)
    #
    logging-test-driver-nginx:
        image: observabilitystack/logging-test-driver-nginx:2
        environment:
            LOG_LINES_PER_MINUTE: 120

    # Container that emits SpringBoot/Java logs randomly
    #
    # The variable LOG_LINES_PER_MINUTE defines the (approx.) frequency
    # of log line emission. (2/sec in this case)
    #
    logging-test-driver-spring-boot:
        image: observabilitystack/logging-test-driver-spring-boot:4
        environment:
            LOG_LINES_PER_MINUTE: 120
