---
spring:
  main:
    banner-mode: "off"
---
spring:
  profiles: plain
logging:
  config: "classpath:log4j2-plain.xml"
---
spring:
  profiles: json
logging:
  config: "classpath:log4j2-json.xml"
---

